### ISSUE TITLE
SUGGESTION: Add Auto Disc Mounting Support for the CD Version of Final Fantasy VIII.

### ISSUE THREAD

**Issue by MontyJack2020** [tsunamods-codes/Junction-VIII#9]
Hello,

I was wondering if it would be possible to add auto disc mounting support to this mod manager (similar to what there is in 7th Heaven) for the 2000 disc version of the game? It would save having to mount and unmount the disc images each time.

Many Thanks

**Comment by julianxhokaxhiu** [comment]
This is a behavior that will never come to Junction VIII, as much as it doesn't exist anymore on 7th Heaven. Discs are now only for the ones who officially have a physical copy of the game. For anyone who doesn't Steam is the digital edition officially supported. If you own the disks however, feel free to put them on your Disk drive and Junction VIII will auto detect for you the unit letter, and ensure it is updated accordingly to help the game discover where it is. Hope this helps, cheers!
